name: PR Verify

on:
  workflow_dispatch: 
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build and Test
        run: ./build.ps1
        shell: pwsh
        working-directory: .